#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in8,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl3,  descorerLimit,  sensorTouch)
#pragma config(Sensor, I2C_1,  rightQuad,      sensorNone)
#pragma config(Sensor, I2C_2,  leftQuad,       sensorNone)
#pragma config(Motor,  port2,           DriveLeft_1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           DriveLeft_2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           DriveRight_1,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           DriveRight_2,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           indexer,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           frontRoller,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           descorer,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           flywheel,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify
#pragma platform(VEX2)


// Select Download method as "competition"


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task fullAllMotors() {
	motor[DriveLeft_1] = 127;
	motor[DriveLeft_2] = 127;
	motor[DriveRight_1] = 127;
	motor[DriveRight_2] = 127;
}
task fullReverse() {
	motor[DriveLeft_1] = -127;
	motor[DriveLeft_2] = -127;
	motor[DriveRight_1] = -127;
	motor[DriveRight_2] = -127;
}
task stopMotors() {
	motor(DriveLeft_1) = 0;
	motor(DriveLeft_2) = 0;
	motor(DriveRight_1) = 0;
	motor(DriveRight_1) = 0;

}

task autonomous() {
SensorValue[rightQuad] = 0;
	SensorValue[leftQuad] = 0;
	while(SensorValue[rightQuad] < 1250) {
		startTask(fullAllMotors);
		motor[frontRoller] = 100;
	}

	startTask(fullReverse);
	wait(.25);
	//startTask(stopMotors);
	//wait(2);
	while(SensorValue[rightQuad] > 0) {
		startTask(fullReverse);
	}
	//startTask(fullAllMotors);
	//wait(.25);
	motor[frontRoller] = 0;
	startTask(stopMotors);
	SensorValue[rightQuad] = 0;
//Completely clear out any previous sensor readings by setting the port to "sensorNone"
 SensorType[in8] = sensorNone;
 wait1Msec(500);
 //Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
 SensorType[in8] = sensorGyro;
 wait1Msec(750);

//Adjust SensorScale to correct the scaling for your gyro
 //SensorScale[in8] = 260;
 //Adjust SensorFullCount to set the "rollover" point. 3600 sets the rollover point to +/-3600
 //SensorFullCount[in8] = 3600;

//Specify the number of degrees for the robot to turn (1 degree = 10, or 900 = 90 degrees)
 int degrees10 = 450;

//While the absolute value of the gyro is less than the desired rotation...
 while(abs(SensorValue[in8]) < degrees10)
 {
 //...continue turning
 motor[DriveRight_1] = 60;
 motor[DriveRight_2] = 60;
 motor[DriveLeft_1] = -60;
 motor[DriveLeft_2] = -60;
 }

//Brief brake to stop some drift
 motor[DriveRight_1] = -60;
 motor[DriveRight_2] = -60;
 motor[DriveLeft_1] = 60;
 motor[DriveLeft_2] = 60;
 wait1Msec(250);


}
#define     JOY_DRIVE_V     vexJSLeftV
#define     JOY_DRIVE_H     vexJSLeftH
#define     JOY_THRESHOLD   15


#define MOTOR_NUM               kNumbOfTotalMotors
#define MOTOR_MAX_VALUE         127
#define MOTOR_MIN_VALUE         (-127)
#define MOTOR_DEFAULT_SLEW_RATE 9      // Default will cause 375mS from full fwd to rev
#define MOTOR_FAST_SLEW_RATE    250     // essentially off
#define MOTOR_TASK_DELAY        10      // task 1/frequency in mS (about 66Hz)
#define MOTOR_DEADBAND          9

// Array to hold requested speed for the motors
int motorReq[ MOTOR_NUM ];

// Array to hold "slew rate" for the motors, the maximum change every time the task
// runs checking current mootor speed.
int motorSlew[ MOTOR_NUM ];
task MotorSlewRateTask()
{
	int motorIndex;
	int motorTmp;

	// Initialize stuff
	for(motorIndex=0;motorIndex<MOTOR_NUM;motorIndex++)
	{
		motorReq[motorIndex] = 0;
		motorSlew[motorIndex] = MOTOR_DEFAULT_SLEW_RATE;
	}

	// run task until stopped
	while( true )
	{
		// run loop for every motor
		for( motorIndex=0; motorIndex<MOTOR_NUM; motorIndex++)
		{
			// So we don't keep accessing the internal storage
			motorTmp = motor[ motorIndex ];

			// Do we need to change the motor value ?
			if( motorTmp != motorReq[motorIndex] )
			{
				// increasing motor value
				if( motorReq[motorIndex] > motorTmp )
				{
					motorTmp += motorSlew[motorIndex];
					// limit
					if( motorTmp > motorReq[motorIndex] )
						motorTmp = motorReq[motorIndex];
				}

				// decreasing motor value
				if( motorReq[motorIndex] < motorTmp )
				{
					motorTmp -= motorSlew[motorIndex];
					// limit
					if( motorTmp < motorReq[motorIndex] )
						motorTmp = motorReq[motorIndex];
				}

				// finally set motor
				motor[motorIndex] = motorTmp;
			}
		}

		// Wait approx the speed of motor update over the spi bus
		wait1Msec( MOTOR_TASK_DELAY );
	}
}


void
DriveLeftMotor( int value )
{
	motorReq[ DriveLeft_1 ] = value;
	motorReq[ DriveLeft_2 ] = value;
}


void
DriveRightMotor( int value )
{
	motorReq[ DriveRight_1 ] = value;
	motorReq[ DriveRight_2 ] = value;
}


task PlatformDrive ()//to get onto the platform at the end of the match
{
	if(vexRT[Btn8U] == 1) {
		motor[DriveLeft_1] = 127;
		motor[DriveLeft_2] = 127;
		motor[DriveRight_1] = 127;
		motor[DriveRight_2] = 127;
	}

	if(vexRT[Btn8D] == 1) {
		motor[DriveLeft_1] = -127;
		motor[DriveLeft_2] = -127;
		motor[DriveRight_1] = -127;
		motor[DriveRight_2] = -127;
	}
}
task ArcadeDrive()
{
	int    ctl_v;
	int    ctl_h;
	int    drive_l;
	int    drive_r;

	// Basic arcade control
	while( true )
	{
		// Get joystick H and V control
		ctl_v = vexRT[ JOY_DRIVE_V ];
		ctl_h = -vexRT[ JOY_DRIVE_H ];

		// Ignore joystick near center
		if( (abs(ctl_v) <= JOY_THRESHOLD) && (abs(ctl_h) <= JOY_THRESHOLD) )
		{
			drive_l = 0;
			drive_r = 0;
		}
		else
		{
			// Create drive for left and right motors
			drive_l = (ctl_v + ctl_h) / 2;
			drive_r = (ctl_v - ctl_h) / 2;
		}

		// Now send out to motors
		DriveLeftMotor( drive_l );
		DriveRightMotor( drive_r );

		// don't hog CPU
		wait1Msec( 25 );
	}
}
//task clawControl() {
//	while(true) {
//		if(vexRT[Btn8D] == 1) {
//			motor[clawMotor] = 100;
//		}
//		if(vexRT[Btn8U] == 1) {
//			motor[clawMotor] = -100;
//		}
//	}
//}
task descorerControl() {
	while(true) {
		if(SensorValue[descorerLimit] == 0) {
			motor[descorer] = vexRT[Ch2];
		}
		else {
			if(vexRT[Ch2] > 0) {
				motor[descorer] = -vexRT[Ch2];
			}
			else {
				motor[descorer] = vexRT[Ch2];
			}
		}
	}
}

task frontControl() {
	while(true) {
		if(vexRT[Btn5D] == 1) {
			motor[frontRoller] = 127;
		}
		if(vexRT[Btn6D] == 1) {
			motor[frontRoller] = -127;
		}
	}
}
task flywheelCtrl() {
	while(true) {
		if(vexRT[Btn6U] == 1) {

			motor[flywheel] = -127;
		}
		if(vexRT[Btn5U] == 1) {
			motor[indexer] = 127;
			motor[frontRoller] = 127;
		}
	}
}

//task liftControl() {
//	while(true) {
//		motor[liftMotors] = vexRT[Ch2];
//	}
//}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop
	startTask(MotorSlewRateTask);
	startTask(ArcadeDrive);
	while (true)
	{
		//startTask(liftControl);
		//startTask(clawControl);
		startTask(flywheelCtrl);
		startTask(frontControl);
		startTask(PlatformDrive);
		startTask(descorerControl);
	}
}
